# Generated by Django 5.2 on 2026-01-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='credentials.profile'),
        ),
    ]
