# Generated by Django 5.2 on 2026-02-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_alter_profile_slug'),
        ('credentials', '0003_profile_followers'),
    ]

    operations = [
    ]
